//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 大配件管理系统.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsInfor
    {
        public string PartsID { get; set; }
        public string PartsName { get; set; }
        public string Position { get; set; }
        public string Life { get; set; }
        public string PartsType { get; set; }
        public string Manufacturer { get; set; }
        public string Remarks { get; set; }
    }
}
