//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 大配件管理系统.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfor
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string UserAddress { get; set; }
        public string Position { get; set; }
        public string Remarks { get; set; }
        public string Cipher { get; set; }
    }
}
