//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 大配件管理系统.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class 大配件管理系统Entities : DbContext
    {
        public 大配件管理系统Entities()
            : base("name=大配件管理系统Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarParts> CarParts { get; set; }
        public virtual DbSet<EnterRecords> EnterRecords { get; set; }
        public virtual DbSet<OutRecords> OutRecords { get; set; }
        public virtual DbSet<OverhaulInfor> OverhaulInfor { get; set; }
        public virtual DbSet<PartsInfor> PartsInfor { get; set; }
        public virtual DbSet<ReplaceInfor> ReplaceInfor { get; set; }
        public virtual DbSet<UserInfor> UserInfor { get; set; }
        public virtual DbSet<WarehousingRecords> WarehousingRecords { get; set; }
    }
}
